insta/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('user.urls')),
    path('', include('post.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) #media루트 경로를 설정

post/urls.py
from django.urls import path
from . import views

app_name = 'post'

urlpatterns = [
    #post
    path('', views.index, name='index'),
    path('post/all/', views.all_post, name='all-post'),
    path('post/<int:post_id>/detail/', views.post_detail, name='post-detail' ),
    path('post/create/', views.post_create, name='post-create'),
    path('post/<int:post_id>/delete/', views.post_delete, name='post-delete'),
    path('post/<int:post_id>/edit/', views.post_update, name='post-update'),
    
    #comment
    path('comment/<int:comment_id>/create/', views.comment_create, name='comment-create'),
    path('comment/<int:comment_id>/delete/', views.comment_delete, name='comment-delete'),
    path('comment/<int:comment_id>/edit/', views.comment_update, name='comment-update'),
    
    #like
    path('post/<int:post_id>/likes/', views.likes, name='likes'),
    path('users/<int:user_id>/liked_list/', views.liked_list, name='liked-list'),

    #bookmark
    path('post/<int:post_id>/bookmarks/', views.bookmarks, name='bookmarks'),
    path('users/<int:user_id>/bookmarked_list/', views.bookmarked_list, name='bookmarked-list'),

]

user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    #user
    path('signin/',views.signin, name='signin'),
    path('signup/', views.signup, name='signup'),
    path('logout/', views.logout, name='logout'),
    
    #profile
    path('users/<int:user_id>/', views.profile, name='profile'),
    path('edit-profile/<int:user_id>/', views.profile_update, name='profile-update'),
    
    #follow
    path('users/<int:user_id>/follow/', views.process_follow, name='process-follow'),
    path('users/<int:user_id>/followings/', views.following_list, name='following-list'),
    path('users/<int:user_id>/followers/', views.follower_list, name='follower-list'),
    path('users/recommend/', views.recommend_list, name='recommend-list'),
]

user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    profile_image = models.ImageField(
        default="default_profile_pic.jpg",upload_to="profile_pics"
    )
    
    intro = models.CharField(max_length=60, blank=True, null=True)
    #self 자기가 자기자신을 다시 참조하는 것이기 때문에 self라는 인자 줌
    #symmetrical은 대칭을 할지 말지를 결정하는 건데 여기서 이 옵션에 True를 주면 한 사람이 어떤 사람을 팔로우하면 저절로 맞팔이 되게 된다.
    followings = models.ManyToManyField('self', symmetrical=False, blank=True, related_name= 'followers')

user/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import auth
from .models import User
from post.models import Post
from .validators import contains_special_character, contains_uppercase_letter, contains_lowercase_letter, contains_number


# Create your views here.
#template에서 값을 넘겨줄 때 input방식과 form방식이있다.
#template에서 input값으로 데이터 받아오는 방법이 있다
#forms.py를 만들어 필드를 정의한다음  form.is_valid를 사용하여 처리리하는 방법이 있다
#account
def signin(request):
    if request.method == 'GET':
        user = request.user.is_authenticated #bool값으로 True냐 False냐...
        if user:
            return redirect('/')
        else:
            return render(request, 'user/account/login.html')
        
    elif request.method == 'POST':
        email = request.POST.get('email', '')
        username = User.objects.get(email=email)
        password = request.POST.get('password', '')
        me = auth.authenticate(request, username=username, password=password) 
        #authenticate를 오버라이딩해서 username을 email로 받을 수 있게 하는 방법이 있다! (정석 루트)
        if me is not None:  
            auth.login(request, me)
            return redirect('/')
        else:
            return render(request, 'user/account/login.html', {'error':'이메일 혹은 패스워드를 확인 해주세요.'})
    
def signup(request):
    if request.method == 'GET':
        user = request.user.is_authenticated
        if user:
            return redirect('/')
        else:
            return render(request, 'user/account/signup.html')
    elif request.method == "POST":
        email = request.POST.get('email', '')
        username = request.POST.get('username', '')
        password = request.POST.get('password', '')
        password2 = request.POST.get('password2', '')
        
        if password != password2:
            return render(request, 'user/account/signup.html', {'error': '패스워드를 확인 해 주세요.'})
        else:
            if (len(password) < 8 
                or not contains_uppercase_letter(password)
                or not contains_lowercase_letter(password)
                or not contains_number(password) 
                or not contains_special_character(password) 
            ):
                return render(request, 'user/account/signup.html', {'error':'8자 이상의 영문 대/소문자, 숫자, 특수문자 조합이어야 합니다.' })
            
            if email == '' or username == '' or password == '':
                return render(request, 'user/account/signup.html', {'error': '이메일과 사용자 이름과 패스워드는 필수 값입니다.'})

            email_exist_user = User.objects.filter(email=email)
            username_exist_user = User.objects.filter(username=username)
            if email_exist_user or username_exist_user :
                return render(request, 'user/account/signup.html', {'error': '이메일 또는 사용자이름이 이미 존재합니다. '})
            
            else:
                User.objects.create_user(email=email, username=username, password=password)
                return redirect('/account/signin/')
            
@login_required(login_url='user:signin')
def logout(request):
    auth.logout(request)
    return redirect('/account/signin/')

#follow
@login_required(login_url='user:signin')
def process_follow(request, user_id):
    if request.method == 'POST':
        user = User.objects.get(id=user_id)
        if user != request.user:
            if user.followers.filter(id=request.user.id).exists():
                user.followers.remove(request.user)
            else:
                user.followers.add(request.user)
        return redirect(request.META['HTTP_REFERER'])
    
@login_required(login_url='user:signin')
def following_list(request, user_id):
    if request.method == 'GET':
        context = dict()
        context['followings'] = User.objects.get(id=user_id).followings.all()
        context['profile_user_id'] = User.objects.get(id=user_id)
        return render(request, 'user/account/following_list.html', context=context)

@login_required(login_url='user:signin')
def follower_list(request, user_id):
    if request.method == 'GET':
        context = dict()
        context['followers'] = User.objects.get(id=user_id).followers.all()
        context['profile_user_id'] = User.objects.get(id=user_id)
        return render(request, 'user/account/follower_list.html', context=context)
    
@login_required(login_url='user:signin')
def recommend_list(request):
    if request.method == 'GET':
        context = dict()
        context['recommends'] = User.objects.all()
        return render(request, 'user/account/recommend_list.html', context=context)

#profile
@login_required(login_url='user:signin')
def profile(request, user_id):
    if request.method == 'GET':
        context = dict()
        context['profile_user'] = User.objects.get(id=user_id)
        context["user_post"] = Post.objects.filter(author=user_id)#author를 타고 user_id해야함

        return render(request, 'user/account/profile.html', context=context)

@login_required(login_url='user:signin')
def profile_update(request, user_id):
    if request.method == 'GET':
        context = dict()
        context['user'] = User.objects.get(id=user_id)
        return render(request, 'user/account/profile_update_form.html', context=context)
    
    elif request.method == 'POST':
        edit_user = User.objects.get(id=user_id)
        edit_user.username = request.POST.get('username')
        edit_user.profile_image = request.FILES['image']
        edit_user.intro = request.POST.get('intro')
        edit_user.save()
        
        return redirect('user:profile', user_id)
    

user/templates/user/account/follower_list.html
{% extends "../user_base/base_with_header.html" %}

{% load static %}

{% block title %}팔로워 목록 | Sparkling Coffee Club{% endblock title %}

{% block content %}
    <div id="main_container">
        <div class="form_container ">
            <main class="site-body">
                <div class="follow-list">
                    <div class="follow-list-header">
                        <h2>팔로워 ({{ followers.count }})</h2>
                        <a class="back-link" href="{% url 'user:profile' profile_user_id.id %}">프로필로 돌아가기</a>
                    </div>
                    <hr>
                    {% if followers %}
                        <div class="follow-list-block" style="height: 350px; overflow: scroll; overflow-x: hidden;">
                            {% for u in followers %}
                            <div class="follow-list-block-inner" style="display: flex; align-content: center;">
                                <div>
                                    <a class="follow-list-row" href="{% url 'user:profile' u.id %}">
                                        <div
                                            class="cp-avatar medium"
                                            style="background-image: url('{{ u.profile_image.url }}')"></div>
                                    </a>
                                </div>
                                <div style="margin-left: 10px; display: flex; flex-direction: column;">
                                <span class="nickname">{{ u.username }}</span>
                                <span class="intro" style="font-size: 12px;">{{ u.intro }}</span>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                    {% else %}
                        팔로우 없음
                    {% endif %}
                </div>
            </main>
        </div>
    </div>
{% endblock content %}

user/templates/user/account/following_list.html
{% extends "../user_base/base_with_header.html" %}

{% load static %}

{% block title %}팔로잉 목록 | Sparkling Coffee Club{% endblock title %}

{% block content %}
    <div id="main_container">
        <div class="form_container ">
            <main class="site-body">
                <div class="follow-list">
                    <div class="follow-list-header">
                        <h2>팔로잉 ({{ followings.count }})</h2>
                        <a class="back-link" href="{% url 'user:profile' profile_user_id.id %}">프로필로 돌아가기</a>
                    </div>
                    <hr>
                    {% if followings %}
                    <div class="follow-list-block" style="height: 350px; overflow: scroll; overflow-x: hidden;">
                        {% for u in followings %}
                        <div class="follow-list-block-inner" style="display: flex; flex-direction: row; justify-content: space-between;">
                            <div style="display: flex; align-content: center;">
                                <div>
                                <a class="follow-list-row" href="{% url 'user:profile' u.id %}">
                                    <div
                                        class="cp-avatar medium"
                                        style="background-image: url('{{ u.profile_image.url }}')"></div>
                                </a>
                                </div>
                                <div style="margin-left: 10px; display: flex; flex-direction: column;">
                                    <span class="nickname">{{ u.username }}</span>
                                    <span class="intro" style="font-size: 12px;">{{ u.intro }}</span>
                                </div>
                            </div>
                            <div style="margin-right: 20px;">
                                {% if user.is_authenticated and user != u %}
                                <form
                                    class="follow-button"
                                    action="{% url 'user:process-follow' u.id %}"
                                    method="post">
                                    {% csrf_token %}
                                    {% if u in followings %}
                                        <button class="btn btn-link" style="text-decoration: none; border: 0.5px solid lightgray; font-size: 13px; color: black; margin: auto;" type="submit">
                                            언팔로우
                                        </button>
                                    {% else %}
                                        <button class="btn btn-primary" style="font-size: 13px; margin-left: 150px;" type="submit">
                                            팔로우
                                        </button>
                                    {% endif %}
                                </form>
                                {% endif %}
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                    {% else %}
                        팔로잉 없음
                    {% endif %}
                </div>
            </main>
        </div>
    </div>
{% endblock content %}

user/templates/user/account/login.html
{% extends "../user_base/base_with_header.html" %}

{% load static %}

{% block title %}로그인 | Sparkling Coffee Club{% endblock title %}

{% block content %}
    <div id="main_container">
        <div class="form_container ">
            <div class="form">
                <div class="title_cover">
                    <a href="#"><h1 class="sprite_insta_big_logo title"></h1></a>
                </div>
                <form method="post">{% csrf_token %}
                    <div>
                    <input type="email" class="form-control" placeholder="이메일" id="email" name="email" />
                    </div><p>
                    <div>
                    <input type="password" class="form-control" placeholder="비밀번호" id="password" name="password" />
                    </div>
                    <input type="submit" id="submit_btn" value="로그인" class="submit_btn">
                    <p />
                    {% if error %}
                    <div class="alert alert-danger" role="alert">
                        {{ error }}
                    </div>
                    {% endif %}
                    <hr>                        
                    <div class="password_reset_text">
                        <a href="#">비밀번호를 잊으셨나요?</a>
                    </div>
                </form>
                </div>
                <div class="bottom_box">
                <div>
                    <span>계정이 없으신가요?</span>
                <a class="sign_user_btn_color" href="{% url 'user:signup' %}">가입하기</a>
                </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

user/templates/user/account/profile.html
{% extends "../user_base/base_with_header.html" %}

{% load static %}

{% block title %}

    {{ profile_user.username }}| Sparkling Coffee Club

{% endblock title%}

{% block content %}
    <section id="container">
        <div id="main_container">
            <section class="b_inner">
                <div class="hori_cont">
                    <div class="profile_wrap">
                        <div class="profile_img">
                            <img src="{{ profile_user.profile_image.url }}" alt="프로필이미지">
                        </div>
                    </div>
                    <div class="detail">
                        <div class="top">
                            <div class="user_name">{{ profile_user.username }}</div>
                            {% if user.is_authenticated and user != profile_user %}
                            <form
                                class="follow-button"
                                action="{% url 'user:process-follow' profile_user.id %}"
                                method="post">
                                {% csrf_token %}
                                {% if user in profile_user.followers.all %}
                                    <button class="btn btn-link" style="text-decoration: none; border: 0.5px solid lightgray; font-size: 13px; color: black;" type="submit">
                                        언팔로우
                                    </button>
                                {% else %}
                                    <button class="btn btn-primary" style="font-size: 13px;" type="submit">
                                        팔로우
                                    </button>
                                {% endif %}
                            </form>
                            {% endif %}
                            {% if profile_user == user%}
                                <a href="{% url 'user:profile-update' user.id %}" class="profile_edit">프로필 편집</a>
                                <a href="#" style="border: none; width: 65px;">
                                    <div class="sprite_gear_icon"></div>
                                </a>
                            {% endif %} 
                        </div>
                        <div>
                            <p>{{ profile_user.intro }}</p>
                        </div>
                        <div class="middle">
                            <div style="margin-right: 50px;">
                                게시물
                                {{ profile_user.post.count }}
                            </div>
                            <div style="margin-right: 50px;">
                                <a href="{% url 'user:follower-list' profile_user.id %}">
                                    팔로워
                                    {{ profile_user.followers.count }}
                                </a>
                            </div>
                            <div>
                                <a href="{% url 'user:following-list' profile_user.id %}">
                                    팔로잉
                                    {{ profile_user.followings.count }}
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
                <hr size="3">
                {% if user == profile_user %}
                <div
                    style="display: flex; flex-direction: row; justify-content: center; margin-bottom: 20px;">
                    <a href="{% url 'user:profile' user.id %}">
                        <div style="margin-right: 40px; display: flex; justify-content: center;">
                            <div class="sprite_camera_icon" style="margin-right: 10px;"></div>게시글
                        </div>
                    </a>
                    <a href="{% url 'post:liked-list' user.id %}">
                        <div style="margin-right: 40px; display: flex; justify-content: center;">
                            <div class="sprite_heart_icon_outline" style="margin-right: 10px;"></div>좋아요
                        </div>
                    </a>
                </div>
                {% endif %}
                <br>
                <div class="mylist_contents contents_container active">
                    {% if user_post %}
                        {% for post in user_post %}
                            <div class="pic" style="width: 300px; height: 300px;">
                                <a href="{% url 'post:post-detail' post.id %}"><img src="{{ post.image.url }}" alt=""></a>
                            </div>
                        {% endfor %}
                    {% else %}
                    <div style="display: flex; flex-direction: column; align-items: center; margin: auto;">
                        <div class="sprite_post_camera_icon"></div>
                        <div style="margin-top: 10px;">
                            게시물을 추가해주세요
                        </div>
                    </div>
                    {% endif %}
                </div>
            </section>
        </div>
    </section>
{% endblock content %}

user/templates/user/account/profile_update_form.html
{% extends "../user_base/base_with_header.html" %}

{% block title %}회원정보 수정 | Sparkling Coffee Club{% endblock title %}

{% block content %}

<style>
  #nav_div {
    list-style: none;
    height: 60px;
  }

  #nav_div:hover {
    background-color: #eeeeee;
    border-left: solid 3px;
  }

  #nav_a {
    font-size: 18px;
    padding-left: 20px;
    display: block;
    line-height: 60px;
  }

  #nav_a:hover {
    text-decoration: none;
  }

  #side-navbar {
    width: 220px;
    height: 100%;
    float: left;
  }
</style>


<div style="
  width: 950px;
  height: 100%;
  margin: 100px auto;
  background-color: #fff;
  border: 1px solid #e6e6e6;
  margin-bottom: 30px;">


  <!-- side Nav bar -->
  <div id="side-navbar">
    <div class="menu" style="margin-top: 40px;">
      <div id="nav_div"><a id="nav_a" href="{% url 'user:profile-update' user.id  %}">프로필 편집</a></div>
      <div id="nav_div"><a id="nav_a" href="#">비밀번호 변경</a></div>
      <div id="nav_div"><a id="nav_a" href="#">계정 비활성화</a></div>
    </div>
  </div>

  <main style="
    border-radius: 6px;
    margin: 0px 0px 0px 100px;
    padding: 30px 150px;
    width: 100%;">


    <!-- Profile img & name -->
    <div class="title" style="width: 100%;height: 70px; padding-left: 120px;float: left;">
      <div class="profile-pic cp-avatar large"
        style="background-image: url('{{ user.profile_image.url }}'); width:40px; height:40px;float: left;"></div>
      <div style="font-size: 25px;float: left;padding-left: 20px;">{{user.username}}</div>
    </div>

    <!-- contents -->
    <div>
      <form method="post" enctype="multipart/form-data" autocomplete="off">{% csrf_token %}

        <div style="width: 150px; height:50px;float: left;">
          <p style="font-size: 17px; text-align: right;">이름</p>
        </div>

        <div style="width: 75%; float: left;padding-left:30px">
          <div class="mb-3" style="width:450px; height:50px;">
            <input type="text"class="form-control" placeholder="이름" style="width:300px;" value={{ user.username }} name='username'>
          </div>
        </div>

        <div style="width: 150px; height:50px;float: left;">
          <p style="font-size: 17px; text-align: right;">소개</p>
        </div>

        <div style="width: 75%; float: left;padding-left:30px">
          <div class="mb-3" style="width:450px; height:50px;">
            <input type="text"class="form-control" placeholder="소개" style="width:300px;" value='{{ user.intro }}' name='intro'>
          </div>
        </div>

        <div style="width: 150px; height:50px; float: left;">
          <p style="font-size: 17px; text-align: right;">프로필 사진</p>
        </div>

        <div style="width: 75%; float: left;padding-left:30px">
          <div type="file">
            <input type="file" name="image" id="id_photo" required="required" value='image'>
          </div>
        </div>
        
        <div style="width: 100%;min-width: 500px; height: 200px; float: left;padding:0px 0px 0px 180px">
          <div class="buttons">
            <button type="submit" class="btn btn-primary"
            style="margin-bottom:20px;background-color:rgb(0, 149, 247);width: 80px">제출</button>
            <button onclick="{% url 'user:profile' user.id %}" class="btn btn-secondary"
            style="margin-bottom:20px;;width: 80px">취소</button>
          </div>
        </div>
      </form>

    </div>
</div>
</main>

</div>

{% endblock content %}

user/templates/user/account/recommend_list.html
{% extends "../user_base/base_with_header.html" %}

{% block title %}추천 친구 목록 | Sparkling Coffee Club{% endblock title %}

{% load static %}

{% block content %}
<div id="main_container" style="display: flex; margin: auto;">
    <article class="recommend">
        <div class="follow-list-header">
            <h2>회원님을 위한 추천 </h2>
            <a class="back-link" href="{% url 'post:index' %}">돌아가기</a>
        </div>
        <hr>
        <div class="recommend-box" style="height: 350px; overflow: scroll; overflow-x: hidden;">
            <div>
            {% for u in recommends %}
            {% if u != user and user not in u.followers.all %}
                <div style="display: flex; flex-direction: row; justify-content: space-between;">
                    <div style="display: flex; flex-direction: row;">
                        <div>
                            <a class="follow-list-row" href="{% url 'user:profile' u.id %}">
                                <div
                                    class="cp-avatar medium"
                                    style="background-image: url('{{ u.profile_image.url }}')"></div>
                            </a>
                        </div>
                        <div style="margin-left: 10px; display: flex; flex-direction: column;">
                            <span class="nickname">{{ u.username }}</span>
                            <span class="intro" style="font-size: 12px;">{{ u.intro }}</span>
                        </div>
                    </div>
                    <div>
                        <form
                            class="follow-button"
                            action="{% url 'user:process-follow' u.id %}"
                            method="post">
                            {% csrf_token %}
                            {% if u in user.followings %}
                            {% else %}
                                <button class="btn btn-link" style="font-size: 13px; text-decoration: none;" type="submit">
                                    팔로우
                                </button>
                            {% endif %}
                        </form>
                    </div>
                </div>
            {% endif %}
            {% endfor %}
            </div>
        </div>
    </article>
</div>
{% endblock content %}

user/templates/user/account/signup.html
{% extends "../user_base/base_with_header.html" %}

{% load static %}

{% block title %}회원가입 | Sparkling Coffee Club{% endblock title %}

{% block content %}
    <div id="main_container">
        <div class="form_container">
            <div class="form">
                <div class="title_cover">
                    <a href="#">
                        <h1 class="sprite_insta_big_logo title"></h1>
                    </a>
                </div>
                <form method="post" >{% csrf_token %}
                    <div class="sign_up_text">
                    친구들의 사진과 동영상을 보려면 가입하세요. 
                    </div>
                    <p>
                    <hr>
                    <div>
                    <input type="email" class="form-control" placeholder="이메일" id="email" name="email" />
                    </div>
                    <p>
                    <div>
                    <input type="text" class="form-control" placeholder="사용자 이름" id="username" name="username" />
                    </div>
                    <p>
                    <div>
                    <input type="password" class="form-control" placeholder="비밀번호" id="password" name="password" />
                    </div>
                    <p>
                    <div>
                    <input type="password" class="form-control" placeholder="비밀번호 재확인" id="password2" name="password2" />
                    </div>
                    <p>
                    {% if error %}
                        <div class="alert alert-danger" role="alert">
                            {{ error }}
                        </div>
                    {% endif %}
                    <input type="submit" id="submit_btn" value="가입" class="submit_btn">
                </form>
            </div>
            <div class="bottom_box">
                <div>
                    <span>계정이 있으신가요?</span>
                    <a class="sign_user_btn_color" href="{% url 'user:signin' %}" >로그인</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}