insta/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('user.urls')),
    path('', include('post.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) #media루트 경로를 설정

post/urls.py
from django.urls import path
from . import views

app_name = 'post'

urlpatterns = [
    #post
    path('', views.index, name='index'),
    path('post/all/', views.all_post, name='all-post'),
    path('post/<int:post_id>/detail/', views.post_detail, name='post-detail' ),
    path('post/create/', views.post_create, name='post-create'),
    path('post/<int:post_id>/delete/', views.post_delete, name='post-delete'),
    path('post/<int:post_id>/edit/', views.post_update, name='post-update'),
    
    #comment
    path('comment/<int:comment_id>/create/', views.comment_create, name='comment-create'),
    path('comment/<int:comment_id>/delete/', views.comment_delete, name='comment-delete'),
    path('comment/<int:comment_id>/edit/', views.comment_update, name='comment-update'),
    
    #like
    path('post/<int:post_id>/likes/', views.likes, name='likes'),
    path('users/<int:user_id>/liked_list/', views.liked_list, name='liked-list'),

    #bookmark
    path('post/<int:post_id>/bookmarks/', views.bookmarks, name='bookmarks'),
    path('users/<int:user_id>/bookmarked_list/', views.bookmarked_list, name='bookmarked-list'),

]

user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    #user
    path('signin/',views.signin, name='signin'),
    path('signup/', views.signup, name='signup'),
    path('logout/', views.logout, name='logout'),
    
    #profile
    path('users/<int:user_id>/', views.profile, name='profile'),
    path('edit-profile/<int:user_id>/', views.profile_update, name='profile-update'),
    
    #follow
    path('users/<int:user_id>/follow/', views.process_follow, name='process-follow'),
    path('users/<int:user_id>/followings/', views.following_list, name='following-list'),
    path('users/<int:user_id>/followers/', views.follower_list, name='follower-list'),
    path('users/recommend/', views.recommend_list, name='recommend-list'),
]

post/models.py
from django.db import models
from user.models import User

class Post(models.Model):
    image = models.ImageField(upload_to="post_pics")
    content = models.TextField(max_length=180)
    create_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)
    
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='post')
    
    like_authors = models.ManyToManyField(User, related_name='like_posts')
    bookmark_authors = models.ManyToManyField(User, related_name='bookmark_posts')
    
    def __str__(self):
        return self.content
    
class Comment(models.Model):
    content = models.TextField(max_length=50, blank=False)
    create_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)
    
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='comments')
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    
    def __str__(self):
        return self.content

post/views.py
# 리디렉션을 남발하면 서버 터진다...
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .models import Post, Comment
from user.models import User

def index(request):
    if request.method == 'GET':
        user = request.user.is_authenticated
        if user:
            #값을 넘겨 줄떄는 사전형으로 만들어서 하면 깔끔하니 보기가 좋다. 
            # 또 다른 방법으로 넘겨 줄 수 있는데 context={ 'user': user} 이런식으로 가능하다.
            context = dict()
            context['users'] = User.objects.all()
            context['latest_following_post'] = Post.objects.filter(author__followers=request.user).order_by('-create_at')
            return render(request, 'post/post/index.html', context=context)
        return render(request, 'post/post/index.html')

#로그인이 한 사람만 접속이 가능하고 안되어있다면 로그인페이지로!
@login_required(login_url='user:signin')
def all_post(request):
    if request.method == 'GET':
        context = dict()
        context['posts'] = Post.objects.all()
        return render(request, 'post/post/all_post.html', context=context)

@login_required(login_url='user:signin')
def post_detail(request, post_id):
    if request.method == 'GET':
        context = dict()
        context['post'] = Post.objects.get(id=post_id)
        context['users'] = User.objects.all()
        #filter와 get의 차이를 확실히 알아야한다.최신순으로 불러오기!
        context['comments'] = Comment.objects.filter(post_id=post_id).order_by('-create_at')
        return render(request, 'post/post/post_detail.html', context=context)

@login_required(login_url='user:signin')
def post_create(request):
    if request.method == 'GET':
        return render(request, 'post/post/new_post.html')
    
    elif request.method == 'POST':
        user = request.user
        #file을 불러올 때는 FILES['image']로 불러온다 
        image = request.FILES['image']
        content = request.POST.get('content')
        # 1. Post.objects.create로 만드는 법 2. Posts.save()로 만드는 법 
        #author=user도 넣어줘야 query가 비어지지 않는다. 항상 저장할 때는 생각하면서 작성
        Post.objects.create(author=user, image=image, content=content)
        return redirect('/')
    
@login_required(login_url='user:signin')
def post_delete(request, post_id):
    if request.method == 'GET':
        return  render(request, 'post/post/post_confirm_delete.html')
    
    elif request.method == 'POST':
        post = Post.objects.get(id=post_id)
        post.delete()
        return redirect('/')
    
@login_required(login_url='user:signin')
def post_update(request, post_id):
    if request.method == 'GET':
        context = dict()
        context['post'] = Post.objects.get(id=post_id)
        return render(request, 'post/post/edit_post.html', context=context)
    
    elif request.method == 'POST':
        #일단 연결되어있는 post_id랑 연결시켜야함 아니면 새로 생성됨...
        edit_post = Post.objects.get(id=post_id)
        edit_post.image = request.FILES['image']
        edit_post.content = request.POST.get('content')
        edit_post.save()
        
        return redirect('/')
    
@login_required(login_url='user:signin')
def comment_create(request, comment_id):
    if request.method == 'POST':
        user = request.user
        post = Post.objects.get(id=comment_id)
        content = request.POST.get('content')
        #comment = Comment() ->모델 불러오는 법
        #이렇게 하는 방식도 있지만 모델을 불러와서 comment.content = content 로 하는 방법으로 save하는 방식
        Comment.objects.create(content=content, author=user, post=post)
        #post_id와 post.id와 다른 것이다!!!!!!!!!!!!!!!!!
        return redirect('post:post-detail', post.id)
    
@login_required(login_url='user:signin')
def comment_delete(request, comment_id):
    if request.method == 'GET':      
        return render(request, 'post/post/comment_confirm_delete.html' )
    
    elif request.method == 'POST': 
        comment = Comment.objects.get(id=comment_id)
        post_id = comment.post.id
        comment.delete()

        return redirect('post:post-detail', post_id)
        
@login_required(login_url='user:signin')
def comment_update(request, comment_id):
    if request.method == 'GET':
        context = dict()
        context['comment'] = Comment.objects.get(id=comment_id)
        return render(request, 'post/post/comment_update_form.html', context=context)
    
    elif request.method =='POST':
        edit_comment = Comment.objects.get(id=comment_id)
        post_id = edit_comment.post.id
        edit_comment.content = request.POST.get('content')
        edit_comment.save()
        #디테일 페이지로 이동하는 방법 comment로 인자값을 가져온다!
        return redirect('post:post-detail', post_id) #redirect는 url 뿐만아니라 url name도 설정해줄 수 있다.
        #return redirect('/post/detail/'+str(post_id)) #장진님! 이런식으로 디테일 페이지로 이동할 수 있는 방법이 있다

@login_required(login_url='user:signin')
def likes(request, post_id):
    if request.method == 'POST':
        post = Post.objects.get(id=post_id)

        if post.like_authors.filter(id=request.user.id).exists(): 
            post.like_authors.remove(request.user)
        else:
            post.like_authors.add(request.user)
        return redirect(request.META['HTTP_REFERER']) #현재페이지로 리다이렉트 함!

@login_required(login_url='user:signin')
def liked_list(request, user_id):
    if request.method == 'GET':
        context = dict()
        context['profile_user'] = User.objects.get(id=user_id)
        context["liked_posts"] = Post.objects.filter(like_authors=user_id)
        
        return render(request, 'post/post/post_like_list.html', context=context)

@login_required(login_url='user:signin')
def bookmarks(request, post_id):
    if request.method == 'POST':
        post = Post.objects.get(id=post_id)

        if post.bookmark_authors.filter(id=request.user.id).exists(): 
            post.bookmark_authors.remove(request.user)
        else:
            post.bookmark_authors.add(request.user)
        return redirect(request.META['HTTP_REFERER']) #현재페이지로 리다이렉트 함!

@login_required(login_url='user:signin')
def bookmarked_list(request, user_id):
    if request.method == 'GET':
        context = dict()
        context['profile_user'] = User.objects.get(id=user_id)
        context["bookmarked_posts"] = Post.objects.filter(bookmark_authors=user_id)
        
        return render(request, 'post/post/post_bookmark_list.html', context=context)

post/templates/post/post_base/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'user/styles/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'user/styles/styles.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'user/styles/theme.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'user/styles/login.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'user/styles/common.css' %}">
    <link rel="shortcut icon" type="image/png" href="{% static 'user/favicon/favicon.ico' %}">
    <script src="https://use.fontawesome.com/releases/v5.2.0/js/all.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>


    <title>{% block title %}Sparkling Coffee Club{% endblock title %}</title>
  </head>
  <body>
    {% block header %}{% endblock header %}
    {% block content %}{% endblock content %}
  </body>
</html>

post/templates/post/post_base/base_detail.html
{% load static %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'user/styles/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'user/styles/theme.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'user/styles/styles.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'user/styles/common.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'user/styles/detail-page.css' %}">
    <link rel="shortcut icon" type="image/png" href="{% static 'user/favicon/favicon.ico' %}">
    <script src="https://use.fontawesome.com/releases/v5.2.0/js/all.js"></script>
    {% block post-detail-style %} {% endblock %}
    <title>{% block title %}Sparkling Coffee Club{% endblock title %}</title>
  </head>
  <body>
    {% block header %}{% endblock header %}
    {% block content %}{% endblock content %}
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="{% static 'user/js/main.js' %}"></script>
    
</body>
</html>

post/templates/post/post_base/base_detail_with_header.html
{% extends "../post_base/base_detail.html" %}
{% load static %}

{% block header %}

{% if user.is_authenticated %}
    <section id="container">
        <header id="header">
            <section class="inner">
                <h1 class="logo">
                    <a href="{% url 'post:index' %}">
                        <div class="sprite_write_logo"></div>
                    </a>
                </h1>
                <div class="right_icons">
                    <a href="{% url 'post:post-create' %}">
                        <div class="sprite_camera_icon"></div>
                    </a>
                    <a href="{% url 'post:all-post' %}">
                        <div class="sprite_compass_icon"></div>
                    </a>
                    <a href="#">
                        <div class="sprite_heart_icon_outline"></div>
                    </a>
                    <a href="{% url 'user:profile' user.id %}">
                        <div class="sprite_user_icon_outline"></div>
                    </a>
                    <a href="{% url 'user:logout' %}">
                        <div class="sprite_unlock_icon"></div>
                    </a>
                </div>
            </section>
        </header>
    </section>
{% else %}
    <header id="header">
        <section class="h_inner">
            <h1 class="logo">
                <div OnClick="location.href ='{% url 'user:signin' %}'" style="cursor:pointer;" class="sprite_write_logo"></div>
            </h1>
        </section>
    </header>
{% endif %}

{% endblock header %}

post/templates/post/post_base/base_with_header.html
{% extends "../post_base/base.html" %}
{% load static %}

{% block header %}

{% if user.is_authenticated %}
    <section id="container">
        <header id="header">
            <section class="inner">
                <h1 class="logo">
                    <a href="{% url 'post:index' %}">
                        <div class="sprite_write_logo"></div>
                    </a>
                </h1>
                <div class="right_icons">
                    <a href="{% url 'post:post-create' %}">
                        <div class="sprite_camera_icon"></div>
                    </a>
                    <a href="{% url 'post:all-post' %}">
                        <div class="sprite_compass_icon"></div>
                    </a>
                    <a href="#">
                        <div class="sprite_heart_icon_outline"></div>
                    </a>
                    <a href="{% url 'user:profile' user.id %}">
                        <div class="sprite_user_icon_outline"></div>
                    </a>
                    <a href="{% url 'user:logout' %}">
                        <div class="sprite_unlock_icon"></div>
                    </a>
                </div>
            </section>
        </header>
    </section>
{% else %}
    <header id="header">
        <section class="h_inner">
            <h1 class="logo">
                <div OnClick="location.href ='{% url 'user:signin' %}'" style="cursor:pointer;" class="sprite_write_logo"></div>
            </h1>
        </section>
    </header>
{% endif %}

{% endblock header %}