insta/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('user.urls')),
    path('', include('post.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) #media루트 경로를 설정

post/urls.py
from django.urls import path
from . import views

app_name = 'post'

urlpatterns = [
    #post
    path('', views.index, name='index'),
    path('post/all/', views.all_post, name='all-post'),
    path('post/<int:post_id>/detail/', views.post_detail, name='post-detail' ),
    path('post/create/', views.post_create, name='post-create'),
    path('post/<int:post_id>/delete/', views.post_delete, name='post-delete'),
    path('post/<int:post_id>/edit/', views.post_update, name='post-update'),
    
    #comment
    path('comment/<int:comment_id>/create/', views.comment_create, name='comment-create'),
    path('comment/<int:comment_id>/delete/', views.comment_delete, name='comment-delete'),
    path('comment/<int:comment_id>/edit/', views.comment_update, name='comment-update'),
    
    #like
    path('post/<int:post_id>/likes/', views.likes, name='likes'),
    path('users/<int:user_id>/liked_list/', views.liked_list, name='liked-list'),

    #bookmark
    path('post/<int:post_id>/bookmarks/', views.bookmarks, name='bookmarks'),
    path('users/<int:user_id>/bookmarked_list/', views.bookmarked_list, name='bookmarked-list'),

]

user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    #user
    path('signin/',views.signin, name='signin'),
    path('signup/', views.signup, name='signup'),
    path('logout/', views.logout, name='logout'),
    
    #profile
    path('users/<int:user_id>/', views.profile, name='profile'),
    path('edit-profile/<int:user_id>/', views.profile_update, name='profile-update'),
    
    #follow
    path('users/<int:user_id>/follow/', views.process_follow, name='process-follow'),
    path('users/<int:user_id>/followings/', views.following_list, name='following-list'),
    path('users/<int:user_id>/followers/', views.follower_list, name='follower-list'),
    path('users/recommend/', views.recommend_list, name='recommend-list'),
]

post/models.py
from django.db import models
from user.models import User

class Post(models.Model):
    image = models.ImageField(upload_to="post_pics")
    content = models.TextField(max_length=180)
    create_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)
    
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='post')
    
    like_authors = models.ManyToManyField(User, related_name='like_posts')
    bookmark_authors = models.ManyToManyField(User, related_name='bookmark_posts')
    
    def __str__(self):
        return self.content
    
class Comment(models.Model):
    content = models.TextField(max_length=50, blank=False)
    create_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)
    
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='comments')
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    
    def __str__(self):
        return self.content

post/views.py
# 리디렉션을 남발하면 서버 터진다...
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .models import Post, Comment
from user.models import User

def index(request):
    if request.method == 'GET':
        user = request.user.is_authenticated
        if user:
            #값을 넘겨 줄떄는 사전형으로 만들어서 하면 깔끔하니 보기가 좋다. 
            # 또 다른 방법으로 넘겨 줄 수 있는데 context={ 'user': user} 이런식으로 가능하다.
            context = dict()
            context['users'] = User.objects.all()
            context['latest_following_post'] = Post.objects.filter(author__followers=request.user).order_by('-create_at')
            return render(request, 'post/post/index.html', context=context)
        return render(request, 'post/post/index.html')

#로그인이 한 사람만 접속이 가능하고 안되어있다면 로그인페이지로!
@login_required(login_url='user:signin')
def all_post(request):
    if request.method == 'GET':
        context = dict()
        context['posts'] = Post.objects.all()
        return render(request, 'post/post/all_post.html', context=context)

@login_required(login_url='user:signin')
def post_detail(request, post_id):
    if request.method == 'GET':
        context = dict()
        context['post'] = Post.objects.get(id=post_id)
        context['users'] = User.objects.all()
        #filter와 get의 차이를 확실히 알아야한다.최신순으로 불러오기!
        context['comments'] = Comment.objects.filter(post_id=post_id).order_by('-create_at')
        return render(request, 'post/post/post_detail.html', context=context)

@login_required(login_url='user:signin')
def post_create(request):
    if request.method == 'GET':
        return render(request, 'post/post/new_post.html')
    
    elif request.method == 'POST':
        user = request.user
        #file을 불러올 때는 FILES['image']로 불러온다 
        image = request.FILES['image']
        content = request.POST.get('content')
        # 1. Post.objects.create로 만드는 법 2. Posts.save()로 만드는 법 
        #author=user도 넣어줘야 query가 비어지지 않는다. 항상 저장할 때는 생각하면서 작성
        Post.objects.create(author=user, image=image, content=content)
        return redirect('/')
    
@login_required(login_url='user:signin')
def post_delete(request, post_id):
    if request.method == 'GET':
        return  render(request, 'post/post/post_confirm_delete.html')
    
    elif request.method == 'POST':
        post = Post.objects.get(id=post_id)
        post.delete()
        return redirect('/')
    
@login_required(login_url='user:signin')
def post_update(request, post_id):
    if request.method == 'GET':
        context = dict()
        context['post'] = Post.objects.get(id=post_id)
        return render(request, 'post/post/edit_post.html', context=context)
    
    elif request.method == 'POST':
        #일단 연결되어있는 post_id랑 연결시켜야함 아니면 새로 생성됨...
        edit_post = Post.objects.get(id=post_id)
        edit_post.image = request.FILES['image']
        edit_post.content = request.POST.get('content')
        edit_post.save()
        
        return redirect('/')
    
@login_required(login_url='user:signin')
def comment_create(request, comment_id):
    if request.method == 'POST':
        user = request.user
        post = Post.objects.get(id=comment_id)
        content = request.POST.get('content')
        #comment = Comment() ->모델 불러오는 법
        #이렇게 하는 방식도 있지만 모델을 불러와서 comment.content = content 로 하는 방법으로 save하는 방식
        Comment.objects.create(content=content, author=user, post=post)
        #post_id와 post.id와 다른 것이다!!!!!!!!!!!!!!!!!
        return redirect('post:post-detail', post.id)
    
@login_required(login_url='user:signin')
def comment_delete(request, comment_id):
    if request.method == 'GET':      
        return render(request, 'post/post/comment_confirm_delete.html' )
    
    elif request.method == 'POST': 
        comment = Comment.objects.get(id=comment_id)
        post_id = comment.post.id
        comment.delete()

        return redirect('post:post-detail', post_id)
        
@login_required(login_url='user:signin')
def comment_update(request, comment_id):
    if request.method == 'GET':
        context = dict()
        context['comment'] = Comment.objects.get(id=comment_id)
        return render(request, 'post/post/comment_update_form.html', context=context)
    
    elif request.method =='POST':
        edit_comment = Comment.objects.get(id=comment_id)
        post_id = edit_comment.post.id
        edit_comment.content = request.POST.get('content')
        edit_comment.save()
        #디테일 페이지로 이동하는 방법 comment로 인자값을 가져온다!
        return redirect('post:post-detail', post_id) #redirect는 url 뿐만아니라 url name도 설정해줄 수 있다.
        #return redirect('/post/detail/'+str(post_id)) #장진님! 이런식으로 디테일 페이지로 이동할 수 있는 방법이 있다

@login_required(login_url='user:signin')
def likes(request, post_id):
    if request.method == 'POST':
        post = Post.objects.get(id=post_id)

        if post.like_authors.filter(id=request.user.id).exists(): 
            post.like_authors.remove(request.user)
        else:
            post.like_authors.add(request.user)
        return redirect(request.META['HTTP_REFERER']) #현재페이지로 리다이렉트 함!

@login_required(login_url='user:signin')
def liked_list(request, user_id):
    if request.method == 'GET':
        context = dict()
        context['profile_user'] = User.objects.get(id=user_id)
        context["liked_posts"] = Post.objects.filter(like_authors=user_id)
        
        return render(request, 'post/post/post_like_list.html', context=context)

@login_required(login_url='user:signin')
def bookmarks(request, post_id):
    if request.method == 'POST':
        post = Post.objects.get(id=post_id)

        if post.bookmark_authors.filter(id=request.user.id).exists(): 
            post.bookmark_authors.remove(request.user)
        else:
            post.bookmark_authors.add(request.user)
        return redirect(request.META['HTTP_REFERER']) #현재페이지로 리다이렉트 함!

@login_required(login_url='user:signin')
def bookmarked_list(request, user_id):
    if request.method == 'GET':
        context = dict()
        context['profile_user'] = User.objects.get(id=user_id)
        context["bookmarked_posts"] = Post.objects.filter(bookmark_authors=user_id)
        
        return render(request, 'post/post/post_bookmark_list.html', context=context)

post/templates/post/post/follower_list.html
{% extends "../post_base/base_with_header.html" %}

{% load static %}

{% block title %}팔로워 목록 | Sparkling Coffee Club{% endblock title %}

{% block content %}
    <div id="main_container">
        <div class="form_container ">
            <main class="site-body">
                <div class="follow-list">
                    <div class="follow-list-header">
                        <h2>팔로워 ({{ followers.count }})</h2>
                        <a class="back-link" href="{% url 'post:profile' profile_user_id.id %}">프로필로 돌아가기</a>
                    </div>
                    <hr>
                    {% if followers %}
                        <div class="follow-list-block" style="height: 350px; overflow: scroll; overflow-x: hidden;">
                            {% for u in followers %}
                            <div class="follow-list-block-inner" style="display: flex; align-content: center;">
                                <div>
                                    <a class="follow-list-row" href="{% url 'post:profile' u.id %}">
                                        <div
                                            class="cp-avatar medium"
                                            style="background-image: url('{{ u.profile_image.url }}')"></div>
                                    </a>
                                </div>
                                <div style="margin-left: 10px; display: flex; flex-direction: column;">
                                <span class="nickname">{{ u.username }}</span>
                                <span class="intro" style="font-size: 12px;">{{ u.intro }}</span>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                    {% else %}
                        팔로우 없음
                    {% endif %}
                </div>
            </main>
        </div>
    </div>
{% endblock content %}

post/templates/post/post/index.html
{% extends "../post_base/base_with_header.html" %}

{% load static %}

{% block title %}메인페이지 | Sparkling Coffee Club{% endblock title %}

{% block post-detail-style %}
    <style>
        .detail_comment_field {
            display: flex;
            flex-direction: row;
            justify-content: center;
            align-items: center;
        }
    </style>
{% endblock %}

{% block content %}
    {% if user.is_authenticated %}
        <section id="container">
            <section id="main_container">
                <div class="inner">
                    <div class="contents_box">
                    {% if latest_following_post %}
                        {% for post in latest_following_post %}
                            <article class="contents">
                                <header class="top">
                                    <div class="user_container">
                                        <div class="profile_img">
                                            <a href="{% url 'user:profile' user.id %}">
                                                <img src="{{ post.author.profile_image.url }}" alt="프로필이미지">
                                            </a>
                                        </div>
                                        <div class="user_name">
                                            <div class="nick_name m_text">{{ post.author.username }}</div>
                                            <div class="country s_text">{{ post.author.email }}</div>
                                        </div>

                                    </div>
                                    {% if post.author == user %}
                                        <div class="sprite_more_icon" data-name="more">
                                            <ul class="toggle_box">
                                                <li>
                                                    <a href="{% url 'post:post-update' post.id %}">수정</a>
                                                </li>
                                                <li>
                                                    <a href="{% url 'post:post-delete' post.id %}">삭제</a>
                                                </li>
                                            </ul>
                                        </div>
                                    {% endif %}
                                </header>

                                <div class="img_section">
                                    <div class="trans_inner">
                                        <div><img src="{{ post.image.url }}" alt="visual01"></div>
                                    </div>
                                </div>

                                <div class="bottom_icons">
                                    <div class="left_icons">
                                        <form action="{% url 'post:likes' post.id %}" method="post" id='like_icon' style="display: flex; justify-content: space-between; align-items: center;">{% csrf_token %}
                                            {% if user in post.like_authors.all %}
                                                <button type="submit" class="sprite_heart_icon_outline on" data-name="heartbeat"></button>
                                            {% else %}
                                                <button type="submit" class="sprite_heart_icon_outline" data-name="heartbeat"></button>
                                            {% endif %}
                                        </form>
                                        <a href="{% url 'post:post-detail' post.id %}"><div class="sprite_bubble_icon" style="margin-left:10px; float:right;"></div></a>
                                    </div>
                                    <div class="right_icon">
                                        <form action="{% url 'post:bookmarks' post.id %}" method="post">{% csrf_token %}
                                            {% if user in post.bookmark_authors.all %}
                                                <button type="submit" class="sprite_bookmarks_outline on" ></button>
                                            {% else %}
                                                <button type="submit" class="sprite_bookmarks_outline" ></button>
                                            {% endif %}
                                        </form>
                                    </div>
                                </div>

                                <div class="likes m_text">
                                    좋아요
                                    <span id="like-count-39">{{ post.like_authors.count }}</span>
                                    <span id="bookmark-count-39"></span>
                                    개
                                </div>
                                <div class="comment_container">
                                    <div class="comment" id="comment-list-ajax-post37">
                                        <div class="comment-detail">
                                            <div class="nick_name m_text">{{ post.author.username }}</div>
                                            <div>{{ post.content }}</div>
                                        </div>
                                        <a href="{% url 'post:post-detail' post.id %}" style="color: gray;">댓글 모두 보기</a>
                                    </div>
                                </div>

                                <div class="timer">{{ post.create_at }}</div>

                                <div class="comment_field" id="add-comment-post37">
                                    <form
                                        class="comment-create-form"
                                        action="{% url 'post:comment-create' post.id %}"
                                        method="post">
                                        {% csrf_token %}
                                        <div class="comment_field" style="height: 20px; font-size: 13px;">
                                            <input type="text" placeholder="댓글달기..." name="content">
                                            <button type="submit" style=" border: none; background:none; float:right; font-size : 13px; color: skyblue">게시</button>
                                        </div>
                                    </form>
                                </div>
                            </article>
                        {% endfor %}
                    {% else %}
                    <div style="display: flex; flex-direction: column; align-items: center; margin: 80px 300px 0px 0px;">
                        <div class ="sprite_follow_icon"></div>
                        <div style="margin-top: 20px; font-size: 20px;">
                            팔로우를 추가해주세요
                        </div>
                    </div>
                    {% endif %}

                    </div>
                    <input type="hidden" id="page" value="1">

                    <div class="side_box">
                        <div class="user_profile">
                            <div class="profile_thumb">
                                <a href="{% url 'user:profile' user.id %}">
                                    <img src="{{ user.profile_image.url }}" alt="프로필사진">
                                </a>
                            </div>
                            <div class="detail">
                                <div class="id m_text">{{user.username}}</div>
                                <div class="ko_name">{{user.email}}</div>
                            </div>
                        </div>

                        <article class="recommend">
                            <header class="reco_header">
                                <div>회원님을 위한 추천</div>
                                <a href="{% url 'user:recommend-list' %}">모두 보기</a>
                            </header>
                            <div class="scroll_inner">
                                {% for u in users %}
                                {% if u != user and user not in u.followers.all %}
                                <div class="thumb_user" style="display: flex; flex-direction: row; justify-content: space-between;">
                                    <div style="display: flex; align-content: center;">
                                        <div class="profile_thumb">
                                            <a href="{% url 'user:profile' u.id %}">
                                                <img src="{{ u.profile_image.url }}" alt="프로필사진">
                                            </a>
                                        </div>
                                        <div class="detail">
                                            <div class="id">{{u.username}}</div>
                                        </div>
                                    </div>
                                    <div>
                                        <form
                                            class="follow-button"
                                            action="{% url 'user:process-follow' u.id %}"
                                            method="post">
                                            {% csrf_token %}
                                            {% if u in user.following %}
                                                <button class="btn btn-link" style="text-decoration: none; border: 0.5px solid lightgray; font-size: 13px; color: black;" type="submit">
                                                    언팔로우
                                                </button>
                                            {% else %}
                                                <button class="btn btn-link" style="font-size: 13px; text-decoration: none;" type="submit">
                                                    팔로우
                                                </button>
                                            {% endif %}
                                        </form>
                                    </div>
                                </div>
                                {% endif %}
                                {% endfor %}
                            </div>
                        </article>
                    </div>
                </div>
            </section>
        </section>
    {% else %}
        <div id="main_container">
            <div class="form_container ">
                <div class="form">
                    <div class="sign_up_text">
                        <br>
                        <p>시작하려면 로그인이 필요합니다.
                        </p>
                        <a class="sign_user_btn_color" href="{% url "user:signin" %}">로그인</a>
                        <a class="sign_user_btn_color" href="{% url "user:signup" %}">회원가입</a>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}
{% endblock content %}

post/templates/post/post/post_detail.html
{% extends "../post_base/base_detail_with_header.html" %}

{% block post-detail-style %}
    <style>
        .detail_comment_field {
            display: flex;
            flex-direction: row;
            justify-content: center;
            align-items: center;
        }
    </style>
{% endblock %}

{% block title %}상세페이지 | Sparkling Coffee Club{% endblock title %}

{% block content %}
    <div id="main_container">
        <section class="b_inner">
            <div class="contents_box">
                <article class="contents cont01">
                    <div class="img_section">
                        <div class="trans_inner">
                            <div><img src="{{ post.image.url }}" alt=""></div>
                        </div>
                    </div>
                    <div class="detail--right_box">
                        <header class="top">
                            <div class="user_container" style="align-items:flex-start">
                                <div class="profile_img">
                                        <img src="{{ post.author.profile_image.url }}" alt="프로필 사진">
                                </div>
                                <div class="user_name">
                                    <div class="nick_name">{{post.author.username}}</div>
                                    <div class="country">{{post.author.email}}</div>
                                    <div style="margin-top:20px; word-break:break-all;word-wrap:break-word; width:250px">{{ post.content }}</div>
                                </div>
                            </div>
                            {% if post.author == user %}
                                <div class="sprite_more_icon" data-name="more">
                                    <ul class="toggle_box">
                                        <li>
                                            <a href="{% url 'post:post-update' post.id %}">수정</a>
                                        </li>
                                        <li>
                                            <a href="{% url 'post:post-delete' post.id %}">삭제</a>
                                        </li>
                                    </ul>
                                </div>
                            {% endif %}

                        </header>

                        <section class="scroll_section">
                            {% for comment in comments %}
                                <p>
                                    <p>
                                        <div class="user_container-detail">
                                            <div class="user">
                                                <div class="profile_img">
                                                    <img src="{{ comment.author.profile_image.url }}" alt="프로필 사진">
                                                </div>
                                            </div>
                                            <div class="comment">
                                                <span class="user_id">{{ comment.author.username }}</span>{{ comment.content }}
                                                <div class="time">
                                                    {{ comment.create_at }}</div>
                                                <div class="icon_wrap">
                                                    <div class="more_trigger">
                                                        {% if user == comment.author %}
                                                            <div class="sprite_more_icon" data-name="more">
                                                                <ul class="toggle_box">
                                                                    <li>
                                                                        <a href="{% url 'post:comment-update' comment.id %}">수정</a>
                                                                    </li>
                                                                    <li>
                                                                        <a href="{% url 'post:comment-delete' comment.id %}">삭제</a>
                                                                    </li>
                                                                </ul>
                                                            </div>
                                                        {% endif %}
                                                    </div>
                                                    <div></div>
                                                </div>
                                            </div>
                                        </div>
                            {% endfor %}

                                </section>

                                <div class="bottom_icons">
                                    <div class="left_icons" style="width:100px; height:30px;" >
                                            <form action="{% url 'post:likes' post.id %}" 
                                            method="post">
                                            {% csrf_token %}
                                            {% if user in post.like_authors.all %}
                                                <input
                                                    type="submit"
                                                    value=""
                                                    class="sprite_heart_icon_outline_deatil on"
                                                    name="39"
                                                    data-name="heartbeat"></input>
                                            {% else %}
                                                <input
                                                    type="submit"
                                                    value=""
                                                    class="sprite_heart_icon_outline_deatil"
                                                    name="39"
                                                    data-name="heartbeat"></input>
                                            {% endif %}                                        
                                            <a href="{% url 'post:post-detail' post.id %}">
                                                <div class="sprite_bubble_icon" style="float:right; margin-left:10px;"> </div>
                                            </a>  
                                        </form>                                         
                                    </div>
                                    <div class="right_icon">
                                        <form action="{% url 'post:bookmarks' post.id %}" method="post">{% csrf_token %}
                                        {% if user in post.bookmark_authors.all %}
                                            <button type="submit" class="sprite_bookmarks_outline on" ></button>
                                        {% else %}
                                            <button type="submit" class="sprite_bookmarks_outline" ></button>
                                        {% endif %}
                                        </form>
                                    </div>
                                </div>
                                <div class="count_likes">
                                    좋아요
                                    <span class="count">{{ post.like_authors.count}}</span>
                                    개
                                </div>
                                <div class="timer">{{ post.created_at }}</div>
                                <form
                                    class="comment-create-form"
                                    action="{% url 'post:comment-create' post.id %}"
                                    method="post">
                                    {% csrf_token %}
                                    <div class="detail_comment_field" style="height: 35px; font-size : 13px;">
                                        <input type="text" name='content' placeholder="댓글 달기 ..." style ="border:none; float:left; width:100%;" />
                                        <button
                                            type="submit"
                                            style=" border:none; background:none; float:right; font-size:13px; color:skyblue;">게시</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </article>
                </div>
            </section>
        </div>
    </section>
{% endblock content %}